import { Outfit as OutfitFont, Ovo as OvoFont } from "next/font/google";
import "./globals.css";


const outfit = OutfitFont({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-outfit", // optional but recommended
});

const ovo = OvoFont({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ovo", // optional
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${outfit.variable} ${ovo.className} antialiased leading-8 overflow-x-hidden` }>
  {children}
</body>

    </html>
  );
}
